mqtt:
  host: 192.168.1.35
  user: mqtt_user
  password: swkvyMUdvfqT7xjF3V%f

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  salon:
    ffmpeg:
      inputs:
        - path: rtsp://Palapa:v845TKzgVY!^A%JeyBn6@192.168.1.149/11
          roles:
            - record
            # - detect
    # detect:
    #   fps: 5
    #   treshold: 0.8

record:
  enabled: true
  retain:
    days: 1
  events:
    retain:
      default: 14
snapshots:
  enabled: true

# objects:
#   track:
#     - person
#     - cat
version: 0.14
